### ISSUE TITLE
pass GH_USER/GH_PASS differently

### ISSUE THREAD

**Issue by teto** [AGhost-7/critiq.vim#17]
I would rather pass  GH_USER as a vim variable and GH_PASS in a hidden file or ideally use the keyring.
Lots of cheers from my side, I have been dreaming about such a plugin for quite some time.

**Comment by AGhost-7** [comment]
Keyring is out of the question since I want to preserve the ability to use this tool in a headless environment. Supporting Linux would also probably be quite complicated (since there's more than one keyring program out there AFAIK).

I don't see the security benefit in using a file instead of environment variables. As far as I know this is how most tools work. If you want the information to be encrypted at rest, you can create an encrypted directory and place a file in there which you would then be sourced from your bashrc. For example, in my bashrc I have the following:
```
if [ -f ~/Private/.auth ]; then
  . ~/Private/.auth
fi
```

**Comment by dkvasnicka** [comment]
Isn't it possible to authenticate against GH using some kind of token (generated upon authorization in a browser) instead of using username and password? However you do it it's still a security concern if you require credentials in env variables.

**Comment by teto** [comment]
with environment variables, well pretty much every program can see your password. Using "env" will print the password on console ! I would rather have to type my password when asked as done in 
https://github.com/junegunn/vim-github-dashboard .

**Comment by AGhost-7** [comment]
I don't have the intention of supporting something that I can't guarantee to be portable. Feel free to open a PR, but this isn't a feature that I plan to implement.
